plt_final.py

![image](https://user-images.githubusercontent.com/70520853/166166028-61940587-8962-43d8-a776-665be3ae9e65.png)



plt_cv2.py

![image](https://user-images.githubusercontent.com/70520853/166166046-bda35632-c290-4608-91b9-186c3a6da96b.png)


Tried everything I could but kept getting the same error. I even redownloaded pyhton and its libraries.
